import { rename, writeFile } from 'node:fs/promises';
import { defineConfig } from 'vite';

const stylesheetBase = '/assets/css/';

export default defineConfig({
    input: 'assets/scss/app.scss',
    base: stylesheetBase,
    publicDir: false,
    build: {
        outDir: 'public/assets/css',
        assetsDir: '',
    },
    plugins: [
        {
            name: 'styles-template',
            apply: 'build',
            async writeBundle(_options, bundle) {
                const stylesheet = Object.values(bundle).find(
                    (file) => file.type === 'asset' && file.fileName.endsWith('.css'),
                );

                if (!stylesheet) {
                    this.error('Stylesheet was not generated');
                }

                const templatePath = new URL('./templates/parts/styles.tpl', import.meta.url);
                const temporaryPath = new URL('./templates/parts/styles.tpl.tmp', import.meta.url);
                const template = '{* Generated by Vite from assets/scss/app.scss. *}\n'
                    + `<link rel="stylesheet" href="${stylesheetBase}${stylesheet.fileName}">\n`;

                await writeFile(temporaryPath, template);
                await rename(temporaryPath, templatePath);
            },
        },
    ],
});
